fix(kitex): update client template
cloudwego/cwgo pull request #110
Opened 2023-12-11 13:35 UTC by rogerogers

#### What type of PR is this?

#### What this PR does / why we need it (en: English/zh: Chinese):

en:  fix(kitex): update client template
zh: 更新 kitex client 模板

#### Which issue(s) this PR fixes:

2023-12-11 13:49 UTC, li-jin-gou commented on tpl/kitex/client/standard/init_tpl.yaml
> +    {{- if .HasStreaming }}
这个地方的作用是？

2023-12-11 13:50 UTC, li-jin-gou commented on tpl/kitex/client/standard/init_tpl.yaml
> +        {{- if .HasStreaming }}
还有这里的作用是？

2023-12-11 13:53 UTC, rogerogers commented on tpl/kitex/client/standard/init_tpl.yaml
> +    {{- if .HasStreaming }}
https://github.com/cloudwego/kitex/blob/4db852560728c362ca946096cc62506956794389/tool/internal_pkg/generator/generator.go#L482

2023-12-13 03:26 UTC, li-jin-gou approved these changes

2023-12-13 03:30 UTC, li-jin-gou requested changes

2023-12-13 03:30 UTC, li-jin-gou commented on tpl/kitex/client/standard/client_tpl.yaml
> -  {{- if .Oneway}}
为什么删除了 oneway  的判断

2023-12-13 03:30 UTC, li-jin-gou commented on tpl/kitex/client/standard/client_tpl.yaml
> -  {{- if .Oneway}}
为什么删除了 oneway 的判断

2023-12-13 03:30 UTC, li-jin-gou commented on tpl/kitex/client/standard/init_tpl.yaml
> -        {{- if eq .Codec "thrift"}}
这里为什么删掉

2023-12-13 03:46 UTC, rogerogers commented on tpl/kitex/client/standard/client_tpl.yaml
> -  {{- if .Oneway}}
跟 .Void 判断一个效果

2023-12-13 03:57 UTC, rogerogers commented on tpl/kitex/client/standard/init_tpl.yaml
> -        {{- if eq .Codec "thrift"}}
保留了。

2023-12-13 04:02 UTC, li-jin-gou approved these changes

2023-12-13 04:02 UTC, merged