feat: One stop RPC/HTTP call technology solution
cloudwego/cwgo pull request #80
Opened 2023-08-15 05:46 UTC by StellarisW

#### What type of PR is this?

feature

#### What this PR does / why we need it (en: English/zh: Chinese):

en: 
zh: 增加一站式平台管理，将Server 和 Client 的代码生成工作做到自动化、平台化，通过代码统一托管的方式来提升用户体验

2023-10-03 14:34 UTC, li-jin-gou commented on platform/server/cmd/api/internal/biz/handler/template/add_template.go
> +	templatemodel "github.com/cloudwego/cwgo/platform/server/shared/kitex_gen/template"
hertz 使用 kitex_gen 的场景不需要 kitex 的编解码代码，这里用 kitex_gen 把代码量直接带上来了

2023-10-03 14:35 UTC, li-jin-gou commented on platform/server/cmd/api/internal/biz/handler/repository/delete_repository.go
> +	logger.Logger.Debug("http response args", zap.Reflect("args", res))
统一到中间件打印日志通参

2023-10-04 12:13 UTC, Skyenought commented on platform/server/web/index.html
> +    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
把这个 图标换成 cloudwego 的图标?

2023-10-04 12:48 UTC, Skyenought commented on platform/server/web/src/App.tsx
> +export default function App() {
这个 platform 有计划支持 i18n 吗

2023-10-04 12:49 UTC, Skyenought commented on platform/server/web/.prettierrc.cjs
> +	printWidth: 80,
prettierrc 的设置并没有生效

2023-10-05 11:53 UTC, chaoranz758 commented on platform/server/cmd/api/internal/biz/handler/idl/sync_idls.go
> +)
这些 import path 都 format 一下，其他文件也存在类似问题

2023-10-05 11:56 UTC, StellarisW commented on platform/server/cmd/api/internal/biz/handler/idl/sync_idls.go
> +)
之后会用gofumpt和golangci-lint格式化

2023-12-06 05:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/cwgo?pullRequest=80) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/cwgo?pullRequest=80) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: StellarisW<br/>:white_check_mark: Nihilism0<br/>:white_check_mark: cheerioInf<br/>:x: tanbowen03<br/><hr/>**tanbowen03** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/cwgo?pullRequest=80) it.</sub>

2023-12-10 14:59 UTC, li-jin-gou requested changes

2023-12-10 14:59 UTC, li-jin-gou commented on platform/server/shared/dao/internal/repository/repository.go
> +		IsDeleted:      0,
这里为啥不用 gorm 的软删

2023-12-10 14:59 UTC, li-jin-gou commented on platform/server/shared/dao/internal/repository/repository.go
> +		IsDeleted:      0,
这里也有结构体

2023-12-10 14:59 UTC, li-jin-gou commented on platform/server/shared/dao/internal/idl/idl.go
> +		go func(i int, idl *entity.MysqlIDL) {
开发大忌循环查库，可以改为一条 SQL，批量查询+创建索引

2023-12-10 14:59 UTC, li-jin-gou commented on platform/server/shared/dao/internal/idl/idl.go
> +			// TODO: check
这里 check 啥

2023-12-10 14:59 UTC, li-jin-gou commented
本地在 server 目录下使用 gofumpt -e -d -w -extra .

2023-12-10 16:14 UTC, li-jin-gou requested changes

2023-12-10 16:14 UTC, li-jin-gou commented on platform/server/cmd/api/options.go
> +	flagSet.StringVarP(&o.ServerMode, "server_mode", "", "", "")
完善命令，不用的则去掉

2023-12-10 16:14 UTC, li-jin-gou commented on platform/server/cmd/api/router.go
> +func getPathRewriter(prefix string) app.PathRewriteFunc {
没有被使用的函数

2023-12-10 16:14 UTC, li-jin-gou commented on platform/server/cmd/agent/pkg/generator/cwgo.go
> +		"--module", serviceName,
module 三段式需要拼全 github.com/aa/bb 这样，另外需要替用户执行一下 go mod tidy

2023-12-10 16:19 UTC, li-jin-gou commented on platform/server/idl/api/base.thrift
> +service BaseService {
base 的逻辑是不是可以干掉了，重新 gen 一下代码，去掉无用的依赖

2023-12-10 16:20 UTC, li-jin-gou commented on platform/server/idl/model/user.thrift
> +struct UserInfo{
这个也可以去掉

2023-12-10 16:33 UTC, li-jin-gou requested changes

2023-12-10 16:33 UTC, li-jin-gou commented on platform/server/cmd/api/api.go
> + *  * Copyright 2022 CloudWeGo Authors
license 批量修一下，弄错了。

2023-12-11 13:52 UTC, li-jin-gou commented on platform/server/cmd/agent/pkg/generator/cwgo.go
> +		"--module", serviceName,
希望生成的代码执行 go mod tidy  @StellarisW

2023-12-14 13:37 UTC, rogerogers commented
10万+ 👀

2023-12-15 07:27 UTC, li-jin-gou commented
> 10万+ 👀

9w+ 的 kitex_gen 代码 @rogerogers

2023-12-15 07:30 UTC, StellarisW commented
> > 10万+ 👀
> 
> 9w+ 的 kitex_gen 代码 @rogerogers

别尬黑，kitex_gen 代码只有5w 😇

2023-12-15 08:05 UTC, li-jin-gou commented
> > > 10万+ 👀
> > 
> > 
> > 9w+ 的 kitex_gen 代码 @rogerogers
> 
> 别尬黑，kitex_gen 代码只有5w 😇

hz 的 model 也有，里面默认用 thrfit 会生成解码器函数，重新生成一遍去掉吧，这样就能少一小半了

2023-12-15 08:31 UTC, li-jin-gou requested changes
hz 生成代码时携带 -t=template=slim  参数，去除不需要使用的 thrift 编解码函数

2023-12-18 05:02 UTC, li-jin-gou approved these changes

2023-12-18 05:02 UTC, merged